import os
import logging
import pickle
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# ✅ FIX 1: Corrected Pandas-TA classic library function mappings
import pandas_ta_classic as ta
from config.settings import settings

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("TradingEngine.ModelTrainer")


class TradingModelTrainer:
    """
    Ingests technical feature matrices, structures directional prediction labels,
    trains an XGBoost Classifier machine learning model, and saves binary weights.
    """

    def __init__(self, model_filename: str = "xgboost_v1.pkl"):
        self.model_filename = model_filename

        # ✅ FIX 2: Hard-align the output folder to save straight into the shared assets space
        # This matches exactly where your live AI strategies search for the binary weights!
        self.output_dir = "/app/assets" if os.path.exists("/app") else os.path.join(os.getcwd(), "assets")
        self.output_path = os.path.join(self.output_dir, self.model_filename)

        os.makedirs(self.output_dir, exist_ok=True)

    def prepare_data_matrices(self, historical_df: pd.DataFrame, prediction_horizon: int = 1) -> tuple:
        """
        Calculates mathematical indicator columns via pandas-ta-classic
        and maps future return targets into binary target states (0=Down/Flat, 1=Up).
        """
        if historical_df.empty or len(historical_df) < 30:
            raise ValueError("Insufficient data rows to process feature matrices.")

        df = historical_df.copy()
        df.columns = [col.lower().strip() for col in df.columns]

        # ─── 🛡️ THE COLUMNS INTERFACE HARMONIZER (FIXED) ───
        # Maps 'last_price' coming from the table schema natively as your closing price series!
        if "last_price" in df.columns:
            close_series = df["last_price"]
            df["close"] = df["last_price"]  # Populates 'close' key for pct_change mathematical lookups
        elif "close" in df.columns:
            close_series = df["close"]
        else:
            raise KeyError("Provided dataset structure lacks a valid close or last_price price column.")

        high_series = df.get("high", close_series)
        low_series = df.get("low", close_series)

        # Calculate mathematical indicator columns via pandas-ta-classic functional interfaces
        df["rsi"] = ta.rsi(close_series, length=int(settings.RSI_PERIOD))
        df["sma_fast"] = ta.sma(close_series, length=9)
        df["sma_slow"] = ta.sma(close_series, length=21)

        # Handle complex indicators safely returning default matrices if calculations fail
        macd_df = ta.macd(close_series)
        df["macd"] = macd_df.iloc[:, 0] if macd_df is not None else 0.0

        bb_df = ta.bbands(close_series)
        df["bbl"] = bb_df.iloc[:, 0] if bb_df is not None else 0.0
        df["bbu"] = bb_df.iloc[:, 2] if bb_df is not None else 0.0

        # 2. Construct Predictive Classification Target Matrix (Shifted returns)
        df["future_returns"] = df["close"].pct_change(periods=prediction_horizon).shift(-prediction_horizon)
        df["target"] = np.where(df["future_returns"] > 0, 1, 0)

        # Drop NaN values generated by lookbacks or shift horizons
        df.dropna(inplace=True)

        # 3. Separate Input Arrays from Target Labels
        feature_columns = ["rsi", "sma_fast", "sma_slow", "macd", "bbl", "bbu"]
        X = df[feature_columns]
        y = df["target"]

        return X, y

    def train_and_serialize(self, X: pd.DataFrame, y: pd.Series) -> None:
        """Optimizes tree structures and stores a pickle binary payload to disk."""
        logger.info(f"Splitting structural matrices. Input shapes: {X.shape}")

        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

        model = XGBClassifier(
            n_estimators=100,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            eval_metric="logloss"
        )

        logger.info("Starting XGBoost objective optimization tree routines...")
        model.fit(X_train, y_train)

        predictions = model.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)

        logger.info(f"💥 Machine Learning Model Optimized! Out-of-sample evaluation Accuracy: {accuracy * 100:.2f}%")
        logger.info(f"\n{classification_report(y_test, predictions)}")

        with open(self.output_path, "wb") as f:
            pickle.dump(model, f)

        logger.info(f"💾 Binary file successfully written to disk architecture at: {self.output_path}")


if __name__ == "__main__":
    # Standard script fallback tester
    dates = pd.date_range(start="2025-01-01", periods=500, freq="1h")
    np.random.seed(42)

    mock_close = 150.0 + np.cumsum(np.random.normal(0, 1, 500))
    mock_data = {
        "open": mock_close - 0.5,
        "high": mock_close + 1.0,
        "low": mock_close - 1.0,
        "close": mock_close,
        "volume": np.random.randint(5000, 25000, 500)
    }
    raw_df = pd.DataFrame(mock_data, index=dates)

    trainer = TradingModelTrainer()
    X_mat, y_mat = trainer.prepare_data_matrices(raw_df)
    trainer.train_and_serialize(X_mat, y_mat)
