import os
import logging
import pickle
import numpy as np
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

# Absolute framework imports
import pandas_ta_classic as ta
from config.settings import settings

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("TradingEngine.ModelTrainer")


class TradingModelTrainer:
    """
    Ingests technical feature matrices, structures directional prediction labels,
    trains an XGBoost Classifier machine learning model, and saves binary weights.
    """

    def __init__(self, model_filename: str = "xgboost_v1.pkl"):
        self.model_filename = model_filename
        self.output_dir = os.path.join(os.path.dirname(__file__), "models")
        self.output_path = os.path.join(self.output_dir, self.model_filename)

        # Ensure directories exist within the PyCharm project path
        os.makedirs(self.output_dir, exist_ok=True)

    def prepare_data_matrices(self, historical_df: pd.DataFrame, prediction_horizon: int = 1) -> tuple:
        """
        Calculates mathematical indicator columns via pandas-ta-classic
        and maps future return targets into binary target states (0=Down/Flat, 1=Up).
        """
        if historical_df.empty or len(historical_df) < 30:
            raise ValueError("Insufficient data rows to process feature matrices.")

        df = historical_df.copy()
        df.columns = [col.lower().strip() for col in df.columns]

        # 1. Feature Engineering using the exact same metrics mapping to your live system
        df["rsi"] = df.ta.rsi(length=settings.RSI_PERIOD)
        df["sma_fast"] = df.ta.sma(length=9)
        df["sma_slow"] = df.ta.sma(length=21)

        # Additional features to expand structural signal matrices
        df["macd"] = df.ta.macd().iloc[:, 0] if df.ta.macd() is not None else 0.0
        df["bbl"] = df.ta.bbands().iloc[:, 0] if df.ta.bbands() is not None else 0.0
        df["bbu"] = df.ta.bbands().iloc[:, 2] if df.ta.bbands() is not None else 0.0

        # 2. Construct Predictive Classification Target Matrix (Shifted returns)
        # Calculate percentage returns ahead into the future
        df["future_returns"] = df["close"].pct_change(periods=prediction_horizon).shift(-prediction_horizon)

        # Target label: 1 if future returns are positive, 0 if flat or negative
        df["target"] = np.where(df["future_returns"] > 0, 1, 0)

        # Drop NaN values generated by lookbacks or shift horizons
        df.dropna(inplace=True)

        # 3. Separate Input Arrays from Target Labels
        feature_columns = ["rsi", "sma_fast", "sma_slow", "macd", "bbl", "bbu"]
        X = df[feature_columns]
        y = df["target"]

        return X, y

    def train_and_serialize(self, X: pd.DataFrame, y: pd.Series) -> None:
        """Optimizes tree structures and stores a pickle binary payload to disk."""
        logger.info(f"Splitting structural matrices. Input shapes: {X.shape}")

        # Chronological train-test split pattern to mirror asset sequencing
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

        # Initialize the production XGBoost classifier hyperparameters
        model = XGBClassifier(
            n_estimators=100,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            random_state=42,
            eval_metric="logloss"
        )

        logger.info("Starting XGBoost objective optimization tree routines...")
        model.fit(X_train, y_train)

        # Run out-of-sample metric evaluations
        predictions = model.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)

        logger.info(f"💥 Machine Learning Model Optimized! Out-of-sample evaluation Accuracy: {accuracy * 100:.2f}%")
        logger.info(f"\n{classification_report(y_test, predictions)}")

        # Serialize model binary directly to the project folder layout path
        with open(self.output_path, "wb") as f:
            pickle.dump(model, f)

        logger.info(f"💾 Binary file successfully written to disk architecture at: {self.output_path}")


# Local Context Script Tester
if __name__ == "__main__":
    # Generate synthetic historical dataset dataframe rows to mock real training charts
    dates = pd.date_range(start="2025-01-01", periods=500, freq="1h")
    np.random.seed(42)

    mock_close = 150.0 + np.cumsum(np.random.normal(0, 1, 500))
    mock_data = {
        "open": mock_close - 0.5,
        "high": mock_close + 1.0,
        "low": mock_close - 1.0,
        "close": mock_close,
        "volume": np.random.randint(5000, 25000, 500)
    }
    raw_df = pd.DataFrame(mock_data, index=dates)

    trainer = TradingModelTrainer()
    X_mat, y_mat = trainer.prepare_data_matrices(raw_df)
    trainer.train_and_serialize(X_mat, y_mat)
